#.bash_profile

# To reload it after making changes: `source ~/.bash_profile`

#-------------------------------------------------------------
# Get the aliases and functions
#-------------------------------------------------------------
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi


#-------------------------------------------------------------
# Java Development
#-------------------------------------------------------------
export JAVA_HOME=$HOME/Programs/Java/jdk-11.0.7
export PATH=${JAVA_HOME}/bin:$PATH

export MAVEN_HOME=$HOME/Programs/maven/3.3.9
export PATH=${MAVEN_HOME}/bin:$PATH

export GRADLE_HOME=/opt/Programs/gradle/3.4.1
export PATH=${GRADLE_HOME}/bin:$PATH

export ANDROID_HOME=/opt/android-sdk-linux
export PATH=${ANDROID_HOME}/tools:$PATH
export PATH=${ANDROID_HOME}/platform-tools:$PATH

# Servlet containers
export JBOSS_HOME=/opt/Programs/WildFly/10

export CATALINA_HOME=/opt/Programs/Tomcat/8.5.6
export PATH=${CATALINA_HOME}/bin:$PATH


#-------------------------------------------------------------
# Scala Development
#-------------------------------------------------------------
export SCALA_HOME=$HOME/Programs/scala/2.12.3
export PATH=${SCALA_HOME}/bin:$PATH

export SBT_HOME=$HOME/Programs/sbt/0.13.16
export PATH=${SBT_HOME}/bin:$PATH


#-------------------------------------------------------------
# Javascript Development
#-------------------------------------------------------------
export NODE_HOME=$HOME/Programs/NodeJS/node-v14.2.0-linux-x64
export PATH=${NODE_HOME}/bin:$PATH


#-------------------------------------------------------------
# Go Development
#-------------------------------------------------------------
export PATH=$PATH:/usr/local/go/bin


#-------------------------------------------------------------
# Microsoft Developer Tools
#-------------------------------------------------------------
# .NET 6
export DOTNET_ROOT=${HOME}/Programs/Dotnet/dotnet-sdk-6.0.101-linux-x64
export PATH=$PATH:$DOTNET_ROOT


# Microsoft SQL Server
export PATH=$PATH:/opt/mssql-tools/bin


#-------------------------------------------------------------
# Docker
#-------------------------------------------------------------
DOCKER_CONFIG=$HOME/.docker


#-------------------------------------------------------------
# Other
#-------------------------------------------------------------
export PATH=$PATH:/sbin
export PATH=$PATH:/usr/local/bin
