---
environment_tier: canada
default_region: ca-central-1
region: "{% if override_region != '' %}{{ override_region }}{% else %}{{ default_region }}{% endif %}"
dns_points_to_load_balancer: "{{ load_balancers_enabled | bool }}"
