---
- name: "Security Group | {{ system_role }}"
  ec2_group:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    name: "{{ project }}-{{ system_role }}"
    description: "{{ security_group[system_role].description }}"
    rules: "{{ security_group[system_role].rules }}"
  register: security

- name: "Capture Security Group ID | {{ system_role }}"
  set_fact:
    security_group_id: "{{ security_group_id.update({system_role: security.group_id}) }}{{ security_group_id }}"
