---
- name: Create Elasticache Subnet Group
  elasticache_subnet_group:
    state: present
    name: "{{ project }}-{{ system_role }}"
    description: "Elasticache for {{ project }}"
    region: "{{ region }}"
    subnets: "{{ vpc.subnets | selectattr('resource_tags.Role', 'equalto', system_role) | map(attribute='id') | list }}"

- name: Create Elasticache Nodes
  elasticache:
    state: present

    name: "{{ elasticache_name }}"
    engine: "{{ elasticache_engine }}"
    node_type: "cache.{{ instance_type[system_role] }}"
    num_nodes: 2

    cache_port: "{% if elasticache_engine == 'redis' %}6379{% elif elasticache_engine == 'memcached' %}11211{% endif %}"
    cache_subnet_group: "{{ project }}-{{ system_role }}"
    zone: "{{ region }}{{ preferred_availability_zone }}"
    region: "{{ region }}"

    wait: yes
