---
- name: Request Timestamp
  command: date +%s
  register: date

- name: Capture Timestamp
  set_fact:
    timestamp: "{{ date.stdout }}"

- { include: create/autoscaling.yml, has_load_balancer: False, system_role: management,     when: "'management' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: inbound,        when: "'inbound' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: True,  system_role: application,    when: "'application' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: True,  system_role: applicationapi, when: "'applicationapi' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: True,  system_role: applicationq,   when: "'applicationq' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: cache,          when: "'cache' in required_systems and not using_elasticache" }
- { include: create/autoscaling.yml, has_load_balancer: True,  system_role: outbound,       when: "'outbound' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: aggregator,     when: "'aggregator' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: build,          when: "'build' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: preview,        when: "'preview' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: logs,           when: "'logs' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: metrics,        when: "'metrics' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: client,         when: "'client' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: master,         when: "'master' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: database,         when: "'database' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: database1,         when: "'database1' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: database2,         when: "'database2' in required_systems" }
- { include: create/autoscaling.yml, has_load_balancer: False, system_role: database3,         when: "'database3' in required_systems" }
