---
- set_fact:
    instances: "{{ dict() }}"

- { include: create/instance.yml, system_role: management,     when: "'management' in required_systems" }
- { include: create/instance.yml, system_role: inbound,        when: "'inbound' in required_systems" }
- { include: create/instance.yml, system_role: application,    when: "'application' in required_systems" }
- { include: create/instance.yml, system_role: applicationapi, when: "'applicationapi' in required_systems" }
- { include: create/instance.yml, system_role: applicationq,   when: "'applicationq' in required_systems" }
- { include: create/instance.yml, system_role: cache,          when: "'cache' in required_systems and not using_elasticache" }
- { include: create/instance.yml, system_role: database,       when: "'database' in required_systems and not using_rds" }
- { include: create/instance.yml, system_role: database1,      when: "'database1' in required_systems and not using_rds" }
- { include: create/instance.yml, system_role: database2,      when: "'database2' in required_systems and not using_rds" }
- { include: create/instance.yml, system_role: database3,      when: "'database3' in required_systems and not using_rds" }
- { include: create/instance.yml, system_role: outbound,       when: "'outbound' in required_systems" }
- { include: create/instance.yml, system_role: logs,           when: "'logs' in required_systems" }
- { include: create/instance.yml, system_role: metrics,        when: "'metrics' in required_systems" }
- { include: create/instance.yml, system_role: client,         when: "'client' in required_systems" }
- { include: create/instance.yml, system_role: master,         when: "'master' in required_systems" }
- { include: create/instance.yml, system_role: aggregator,     when: "'aggregator' in required_systems" }
- { include: create/instance.yml, system_role: build,          when: "'build' in required_systems" }
- { include: create/instance.yml, system_role: preview,        when: "'preview' in required_systems" }

- { include: create/rds-database.yml, system_role: database,  when: "'database' in required_systems and using_rds",  tags: ['rds'] }
- { include: create/rds-database.yml, system_role: database1, when: "'database1' in required_systems and using_rds", tags: ['rds'] }
- { include: create/rds-database.yml, system_role: database2, when: "'database2' in required_systems and using_rds", tags: ['rds'] }
- { include: create/rds-database.yml, system_role: database3, when: "'database3' in required_systems and using_rds", tags: ['rds'] }
- { include: create/elasticache.yml, system_role: cache, when: "'cache' in required_systems and using_elasticache",  tags: ['elasticache'] }
