---
- include_vars: "environment_tier/{{ environment_tier | mandatory }}.yml"
- include_vars: infrastructure/subnets.yml
- include_vars: infrastructure/security-groups.yml
- include_vars: infrastructure/load-balancers.yml
- include_vars: infrastructure/instances.yml
- include_vars: "region/{{ region | mandatory }}.yml"

- { include: create/vpc.yml, tags: ['vpc'] }
- { include: security-groups.yml, tags: ['security-group'] }
- { include: load-balancers.yml, tags: ['load-balancer'] }
- { include: instances.yml, tags: ['instances'] }
- { include: autoscaling.yml, tags: ['autoscaling'], when: autoscale | bool }
