---
- set_fact:
    security_group_id: "{{ dict() }}"

- { include: create/security-group.yml, system_role: management }
- { include: create/security-group.yml, system_role: managed }
- { include: create/security-group.yml, system_role: inbound }
- { include: create/security-group.yml, system_role: application }
- { include: create/security-group.yml, system_role: applicationapi }
- { include: create/security-group.yml, system_role: applicationq }
- { include: create/security-group.yml, system_role: cache }
- { include: create/security-group.yml, system_role: database,       when: "'database' in required_systems" }
- { include: create/security-group.yml, system_role: database1,      when: "'database1' in required_systems" }
- { include: create/security-group.yml, system_role: database2,      when: "'database2' in required_systems" }
- { include: create/security-group.yml, system_role: database3,      when: "'database3' in required_systems" }
- { include: create/security-group.yml, system_role: outbound,       when: "'outbound' in required_systems" }
- { include: create/security-group.yml, system_role: aggregator,     when: "'aggregator' in required_systems" }
- { include: create/security-group.yml, system_role: logs,           when: "'logs' in required_systems" }
- { include: create/security-group.yml, system_role: client,         when: "'client' in required_systems" }
- { include: create/security-group.yml, system_role: master,         when: "'master' in required_systems" }
- { include: create/security-group.yml, system_role: metrics,        when: "'metrics' in required_systems" }
- { include: create/security-group.yml, system_role: build,          when: "'build' in required_systems" }
- { include: create/security-group.yml, system_role: preview,        when: "'preview' in required_systems" }

- name: "No Management, Exposing Managed Systems"
  set_fact:
    security_group: "{{ security_group.update(no_management) }}{{ security_group }}"
  when: "'management' not in required_systems"

- { include: create/security-group.yml, system_role: managed, when: "'management' not in required_systems" }

- name: "No Inbound Proxies, Exposing Application Servers"
  set_fact:
    security_group: "{{ security_group.update(no_inbound) }}{{ security_group }}"
  when: "'inbound' not in required_systems"

- { include: create/security-group.yml, system_role: application,    when: "'inbound' not in required_systems" }
- { include: create/security-group.yml, system_role: applicationapi, when: "'inbound' not in required_systems" }
- { include: create/security-group.yml, system_role: applicationq,   when: "'inbound' not in required_systems" }
