---
subnets: "{{ subnets_all | rejectattr('az', 'equalto', region + 'c') | rejectattr('az', 'equalto', region + 'd') | list }}"
preferred_availability_zone: b
availability_zones:
  - eu-central-1a
  - eu-central-1b
