---

- hosts: all
  become: yes
  tasks:
    - name: Install required system packages
      apt: pkg={{ item.name }} state={{ item.state }} update-cache=yes
      with_items:
        - { name: ntp, state: latest }
        - { name: python3, state: latest }
        - { name: python-setuptools, state: latest }
        - { name: python3-setuptools, state: latest }

- hosts: all
  become: true
  roles:
    - {role: ssh-client, tags: [ssh]}
    - {role: python-pip, tags: [pip]}
    - {role: aws-cli, tags: [aws_cli]}
    - {role: postgresql, tags: [database], become: true}
#    - {role: redis, tags: [redis], become: true}
#    - {role: setup, tags: [database], become: true}
#    - {role: rabbitmq, tags: [rabbitmq]}
#    - {role: docker}
#    - {role: nodejs}
#    - {role: R}
#    - {role: RStudio-server}
#    - {role: locale, tags: [locale]}

