---

- hosts: all
  become: yes
  tasks:
    - name: Install required system packages
      apt: pkg={{ item.name }} state={{ item.state }} update-cache=yes
      with_items: 
        - { name: ntp, state: latest }
        - { name: python-pip, state: latest }
        - { name: python3-pip, state: latest }

- hosts: all
  become: true
  roles:
    - {role: locale, tags: [locale]}
    - {role: postgresql, tags: [database], become: true}
    - {role: python-pip, tags: [pip]}
    - {role: aws-cli, tags: [aws_cli]}
    - {role: ssh-client, tags: [ssh]}
#    - {role: rabbitmq, tags: [rabbitmq]}

